### ISSUE TITLE
Spike: Define a way to test modules in development

### ISSUE THREAD

**Issue by trisberg** [spring-cloud/spring-cloud-dataflow-admin-cloudfoundry#13]
As a module developer I'd like to be able to test my modules currently in development using the CF admin. 

It seems that the current module resolution with BUILD-SNAPSHOT version makes this difficult. It requires a temporary repo defined and added to the CD admin. It also seems to require modification of the module definitions with a specific snapshot timestamp version, or faking the module version to something other than BUILD-SNAPSHOT.

**Comment by sabbyanandan** [comment]
Moved to: spring-cloud/spring-cloud-dataflow#234
