### ISSUE TITLE
Use AdminProperties in CloudFoundryModuleDeployerConfiguration

### ISSUE THREAD

**Issue by markpollack** [spring-cloud/spring-cloud-dataflow-admin-cloudfoundry#24]
Admin properties are not being enabled.

**Comment by ericbottard** [comment]
What do you mean?
Le 11 janv. 2016 8:36 PM, "Mark Pollack" <notifications@github.com> a
écrit :

**Comment by markpollack** [comment]
I am wondering why I ended up adding `AdminProperties` in `KubernetesModuleDeployerConfiguration` and we are doing similar in https://github.com/spring-cloud/spring-cloud-dataflow-admin-mesos/pull/14/files   It is just an optimization?

**Comment by ilayaperumalg** [comment]
This [Change] (https://github.com/spring-cloud/spring-cloud-dataflow/commit/0b7548892a79496b0e6d6771e33682b07e09b3c6) we added in spring-cloud-dataflow would have the module launcher (infact the resolver) properties passed via admin as regular command line properties. It is always available for the admin deployers via admin-starter.

**Comment by ericbottard** [comment]
@markpollack I'm wondering: is your admin-starter project up to date? (recently `mvn install`'d)

**Comment by markpollack** [comment]
That is likely the issue, I'll check.  Thanks.

**Comment by markpollack** [comment]
Assuming that is the reason, do we want the CF impl to be aligned with the other impls and explicitly list it?

**Comment by markpollack** [comment]
obsolete
