### ISSUE TITLE
Routes are not deleted when the stream is destroyed

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-dataflow-admin-cloudfoundry#29]
As a user, I tried destroying the stream `time | log`, where `time` and `log` are Boot applications; however, I still see the `routes` even after successful delete of the applications.

**stream:**
```
stream create foo --definition "time | log" --deploy
stream destroy foo
```

**cf cli:**
```
cf routes
Getting routes as sabby ...

space         host                                  domain                   apps
development   foo-log                               app.navy.springapps.io
development   foo-time                              app.navy.springapps.io
```

**Comment by ericbottard** [comment]
It seems there is no easy/reliable way to delete routes for a particular app in the current API, and although routes are not destroyed, it does not prevent application re-deployment.
So I suggest we wait for the new API and see how things behave in that regard there. cc @nebhale

**Comment by trisberg** [comment]
If you want to clean up the orphaned routes you can always run:

    cf delete-orphaned-routes

**Comment by trisberg** [comment]
I think this is behavior is more or less by design. If you have claimed a route it shouldn't necessarily be released if you destroy the associated app. You might want to hold on to and reuse the route.

**Comment by ericbottard** [comment]
> You might want to hold on to and reuse the route.

That's what I thought as well, even though it seems [multiple apps can be bound to a single route](https://github.com/cloudfoundry/cf-java-client/blob/3a702ebd58d06571673396d6b9337745554a4f39/cloudfoundry-client-lib/src/main/java/org/cloudfoundry/client/lib/domain/CloudRoute.java#L50)
