### ISSUE TITLE
404 on M1 release download

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-dataflow-admin-cloudfoundry#31]
As a user, I'm trying to prep SCDF Admin for CF deployment, but I get a 404 on downloading the M1 release from the [reference guide](http://docs.spring.io/spring-cloud-dataflow-admin-cloudfoundry/docs/current-SNAPSHOT/reference/htmlsingle/#getting-started).

**Comment by trisberg** [comment]
Those links for a SNAPSHOT version aren't going to work since there is a build suffix on the file name: http://repo.spring.io/snapshot/org/springframework/cloud/spring-cloud-dataflow-admin/1.0.0.BUILD-SNAPSHOT/spring-cloud-dataflow-admin-1.0.0.BUILD-20151113.100016-78.jar

**Comment by markpollack** [comment]
Guess we need point folks to the snapshot directory then.
