### ISSUE TITLE
Autoconfigure CF Admin Deployer

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-dataflow-admin-cloudfoundry#32]
As a developer, I'd like to `Autoconfigure` CF Admin deployer, so I don't have to do component scanning to discover and register beans at each SPI level.

**Comment by trisberg** [comment]
Has anybody tried to use this on CF? I'm getting the following error when I deploy the admin app:

```
2016-02-08T11:02:52.52-0500 [APP/0]      ERR Caused by: org.springframework.beans.factory.NoUniqueBeanDefinitionException: No qualifying bean of type [javax.sql.DataSource] is defined: expected single matching bean but found 2: mydb,dataSource
```

Also `CloudFoundryModuleDeployerConfiguration` now has spaces instead of tabs for indentation. It should also have copyright year of 2015-2016. Same for `ContextLoadsTests`.

**Comment by ericbottard** [comment]
This seems to be an issue with `DataSourceAutoConfiguration` not detecting that there is already a DataSource available. If you rename your explicit db from `mysql` to `dataSource`, then everything is fine.

**Comment by markpollack** [comment]
before my bad merge. It had been working with binding a 'mysql' service to the admin, which also used DataSourceAutoConfig I would assume.  The new enable annotation should be impacting just how the SPI impl is discovered, but there is some odd side effect it would seem.

**Comment by jvalkeal** [comment]
These seem to be side-effects when a config is moved into auto-configuration and things happen on a different order. https://github.com/spring-cloud/spring-cloud-dataflow/issues/366 is one of those ticking bombs which will blow up if i.e. `EnableDataFlowServer` is moved into auto-config or something else is kicking different order of config use.

Also `DataSourceAutoConfiguration` is a little brittle and I had to exclude its auto-config from gpfdist sink. One thing in `DataSourceAutoConfiguration` may be that it's checking beans of  `DataSource` and `XADataSource` and if explicitly created bean only implements one of those, I think boot does(maybe, possibly) it's own magic.

**Comment by ericbottard** [comment]
One of the problems with our current approach is that
@EnableAutoConfiguration (and hence its excludes) is set on a class that is
in the starter, and so can't be overridden by consumers

**Comment by jvalkeal** [comment]
@ericbottard which starter? Because that's really bad and may cause something I tracked down in https://github.com/spring-cloud/spring-cloud-dataflow/issues/367.

**Comment by markpollack** [comment]
TBH, we have taken the most simple thing in Spring 1.0 - different apps inject a different impl of a strategy interface and made it complex.  That commit in the issue you point to is not an obvious solution.  Maybe we can have several @EnableDataFlow annotation, one for each SPI impl so that they can control what they need to themselves.

**Comment by jvalkeal** [comment]
`@EnableDataFlow` is only enabling shared stuff from admin server(controllers, repos, etc) and afaik there's currently nothing spi specific.

**Comment by markfisher** [comment]
What @jvalkeal said... also, let's avoid doing anything drastic at the `@EnableDataFlowServer` level until we have a better understanding of the boundaries of the generic app-deployer SPI, and specifically what, if anything, has to be configured in addition to that to support the Data Flow Server on each target platform.

**Comment by ericbottard** [comment]
I'm talking about `AdminConfiguration`, which is the one that bears `@EnbleAutoConfiguration`

**Comment by jvalkeal** [comment]
lol, ok, 367 was about removing that `@EnableAutoConfiguration`. We're on a same page here ;)

**Comment by markpollack** [comment]
So w/ the rant over, I think I understand the issue ATM, thanks Janne.   We prob don't even need this configuration class at all (cf auto-reconfiguration would inject the right stuff).  An @ConditionalOnMissingBean for the datasource here seems to work and also if there are tested configuration classes (not needed here, prob a cut-n-paste thing wrt to moving config out of a common admin) they should have @Conditional on them (as ilaya also found in the mesos admin).  I'll try out a few things and hope to get this resolved today.

**Comment by markpollack** [comment]
Long term, want to get away from auto-reconfiguration anyway.

**Comment by markpollack** [comment]
Fixed this by simply removing the explicit configuration and let auto-reconfig handle it for now.
2d7e051dca52a85fa89be36c54452343957cb6a8
