### ISSUE TITLE
Add CI plan for CF deployer

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-dataflow-admin-cloudfoundry#34]
As a developer, I'd like to setup CI plan for CF deployer, so we can validate test suites on incremental code commits.

**Comment by ericbottard** [comment]
Finally, IT'S ALIVE!
see https://build.spring.io/browse/SCD-CFBMASTER-52/log

I'm assigning @sabbyanandan so you can confirm this is done/ok and close the issue

**Comment by sabbyanandan** [comment]
LGTM
