### ISSUE TITLE
Custom port shoud NOT be set for modules

### ISSUE THREAD

**Issue by trisberg** [spring-cloud/spring-cloud-dataflow-admin-cloudfoundry#6]
When deploying a stream module with a custom --port parameter the CF deployment needs to include this port

**Comment by trisberg** [comment]
See https://github.com/spring-cloud/spring-cloud-stream-modules/issues/106

**Comment by ericbottard** [comment]
Changed the description of this issue, as the actual problem is that if one sets a port (via `--server.port`) if conflicts with the auto-configuration and prevents the app from deploying correctly
